-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-12-04 16:29:29 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE historie_ujetych_km (
    id_zaznamu         INTEGER NOT NULL,
    id_vozidla         INTEGER NOT NULL,
    datum_zaznamu      DATE NOT NULL,
    pocet_ujetych_km   INTEGER NOT NULL
);

ALTER TABLE historie_ujetych_km ADD CONSTRAINT historie_ujetych_km_pk PRIMARY KEY ( id_zaznamu );

CREATE TABLE hodnoceni (
    id_hodnoceni     INTEGER NOT NULL,
    id_zakaznika     INTEGER NOT NULL,
    id_zamestnance   INTEGER NOT NULL,
    datum            DATETIME NOT NULL,
    hodnoceni        INTEGER NOT NULL
);

ALTER TABLE hodnoceni ADD CONSTRAINT hodnoceni_pk PRIMARY KEY ( id_hodnoceni );

ALTER TABLE hodnoceni ADD CHECK (hodnoceni BETWEEN 1 AND 10);

CREATE TABLE objednavka (
    id_objednavky     INTEGER NOT NULL,
    id_zakaznika      INTEGER NOT NULL,
    id_zamestnance    INTEGER NOT NULL,
    id_rozvazky       INTEGER NOT NULL,
    datum_vytvoreni   DATETIME NOT NULL,
    cena              INTEGER NOT NULL
);

ALTER TABLE objednavka ADD CONSTRAINT objednavka_pk PRIMARY KEY ( id_objednavky );

CREATE TABLE rozvazka (
    id_rozvazky      INTEGER NOT NULL,
    id_zamestnance   INTEGER NOT NULL,
    id_vozidla       INTEGER NOT NULL,
    cas_odjezdu      DATETIME NOT NULL,
    cas_prijezdu     DATETIME NOT NULL
);

ALTER TABLE rozvazka ADD CONSTRAINT rozvazka_pk PRIMARY KEY ( id_rozvazky );

CREATE TABLE stiznost (
    id_stiznosti     INTEGER NOT NULL,
    id_zakaznika     INTEGER NOT NULL,
    id_zamestnance   INTEGER NOT NULL,
    datum            DATETIME NOT NULL,
    typ_stiznosti    INTEGER NOT NULL
);

ALTER TABLE stiznost ADD CONSTRAINT stiznost_pk PRIMARY KEY ( id_stiznosti );

ALTER TABLE stiznost ADD CHECK (typ_stiznosti BETWEEN 1 AND 6);

CREATE TABLE vozidlo (
    id_vozidla         INTEGER NOT NULL,
    datum_porizeni     DATE NOT NULL,
    cena               INTEGER,
    objem_kufru        INTEGER NOT NULL,
    znacka             VARCHAR(7) NOT NULL,
    pocet_ujetych_km   INTEGER NOT NULL
);

ALTER TABLE vozidlo ADD CONSTRAINT vozidlo_pk PRIMARY KEY ( id_vozidla );

CREATE TABLE zakaznik (
    id_zakaznika      INTEGER NOT NULL,
    jmeno             VARCHAR(20) NOT NULL,
    prijmeni          VARCHAR(20) NOT NULL,
    adresa            VARCHAR(40) NOT NULL,
    telefonni_cislo   VARCHAR(12) NOT NULL
);

ALTER TABLE zakaznik ADD CONSTRAINT zakaznik_pk PRIMARY KEY ( id_zakaznika );

CREATE TABLE zamestnanec (
    id_zamestnance    INTEGER NOT NULL,
    jmeno             VARCHAR(20) NOT NULL,
    prijmeni          VARCHAR(20) NOT NULL,
    adresa            VARCHAR(40) NOT NULL,
    telefonni_cislo   VARCHAR(12) NOT NULL,
    pohlavi           VARCHAR(1) NOT NULL,
    datum_narozeni    DATE NOT NULL,
    datum_nastupu     DATE NOT NULL,
    pozice            VARCHAR(20) NOT NULL
);

ALTER TABLE zamestnanec ADD CONSTRAINT zamestnanec_pk PRIMARY KEY ( id_zamestnance );

ALTER TABLE zamestnanec ADD Check(pohlavi IN ( 'M', 'Z'))

ALTER TABLE historie_ujetych_km
    ADD CONSTRAINT historie_ujetych_km_vozidlo_fk FOREIGN KEY ( id_vozidla )
        REFERENCES vozidlo ( id_vozidla );

ALTER TABLE hodnoceni
    ADD CONSTRAINT hodnoceni_zakaznik_fk FOREIGN KEY ( id_zakaznika )
        REFERENCES zakaznik ( id_zakaznika );

ALTER TABLE hodnoceni
    ADD CONSTRAINT hodnoceni_zamestnanec_fk FOREIGN KEY ( id_zamestnance )
        REFERENCES zamestnanec ( id_zamestnance );

ALTER TABLE objednavka
    ADD CONSTRAINT objednavka_rozvazka_fk FOREIGN KEY ( id_rozvazky )
        REFERENCES rozvazka ( id_rozvazky );

ALTER TABLE objednavka
    ADD CONSTRAINT objednavka_zakaznik_fk FOREIGN KEY ( id_zakaznika )
        REFERENCES zakaznik ( id_zakaznika );

ALTER TABLE objednavka
    ADD CONSTRAINT objednavka_zamestnanec_fk FOREIGN KEY ( id_zamestnance )
        REFERENCES zamestnanec ( id_zamestnance );

ALTER TABLE rozvazka
    ADD CONSTRAINT rozvazka_vozidlo_fk FOREIGN KEY ( id_vozidla )
        REFERENCES vozidlo ( id_vozidla );

ALTER TABLE rozvazka
    ADD CONSTRAINT rozvazka_zamestnanec_fk FOREIGN KEY ( id_zamestnance )
        REFERENCES zamestnanec ( id_zamestnance );

ALTER TABLE stiznost
    ADD CONSTRAINT stiznost_zakaznik_fk FOREIGN KEY ( id_zakaznika )
        REFERENCES zakaznik ( id_zakaznika );

ALTER TABLE stiznost
    ADD CONSTRAINT stiznost_zamestnanec_fk FOREIGN KEY ( id_zamestnance )
        REFERENCES zamestnanec ( id_zamestnance );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

/*
DECLARE @Sql NVARCHAR(500) DECLARE @Cursor CURSOR

SET @Cursor = CURSOR FAST_FORWARD FOR
SELECT DISTINCT sql = 'ALTER TABLE [' + tc2.TABLE_SCHEMA + '].[' +  tc2.TABLE_NAME + '] DROP [' + rc1.CONSTRAINT_NAME + '];'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc1
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc2 ON tc2.CONSTRAINT_NAME =rc1.CONSTRAINT_NAME

OPEN @Cursor FETCH NEXT FROM @Cursor INTO @Sql

WHILE (@@FETCH_STATUS = 0)
BEGIN
Exec sp_executesql @Sql
FETCH NEXT FROM @Cursor INTO @Sql
END

CLOSE @Cursor DEALLOCATE @Cursor
GO

EXEC sp_MSforeachtable 'DROP TABLE ?'
GO
*/
